/**
 * pnpm routes — emits app/(site)/** route files from the inventory.
 *
 * 03-TECHNICAL-SPEC §2 asks for explicit route folders per hub rather than a
 * catch-all, so a URL shape that is not in the inventory has no route at all.
 * Hand-writing thirty near-identical files invites drift, so they are generated
 * from the inventory's real URL shapes and never hand-edited.
 */
import { mkdirSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { inventory } from "../lib/content/inventory";

const SITE_DIR = join(process.cwd(), "app", "(site)");

/** Depth and segment names per hub, derived from the URLs actually present. */
interface Shape {
  /** e.g. ["services", "[service]", "[industry]"] */
  segments: string[];
  archetype: string;
  hub: string;
}

/** Parameter names per archetype, matching the patterns in 00-STRATEGY §3. */
const PARAM_NAMES: Record<string, string[]> = {
  hub: [],
  service: ["service"],
  "service-industry": ["service", "industry"],
  "hire-city": ["slug"],
  "case-study": ["slug"],
  teardown: ["app", "lens"],
  "benchmark-hub": ["metric"],
  benchmark: ["metric", "industry"],
  tool: ["tool"],
  playbook: ["slug"],
  glossary: ["slug"],
  compare: ["slug"],
  template: ["slug"],
  india: ["slug"],
  "pricing-examples": ["category"],
  decision: ["slug"],
  growth: ["problem", "appType"],
};

function shapes(): Shape[] {
  const seen = new Map<string, Shape>();
  for (const row of inventory()) {
    const parts = row.url.split("/").filter(Boolean);
    const params = PARAM_NAMES[row.archetype];
    if (!params) {
      throw new Error(`[routes] no parameter names for archetype "${row.archetype}"`);
    }
    // The first segment is the hub prefix; the rest become dynamic.
    const base = parts.slice(0, parts.length - params.length);
    const segments = [...base, ...params.map((p) => `[${p}]`)];
    const key = segments.join("/");
    if (!seen.has(key)) seen.set(key, { segments, archetype: row.archetype, hub: row.hub });
  }
  return [...seen.values()];
}

function routeSource(s: Shape): string {
  const params = s.segments.filter((x) => x.startsWith("["))
    .map((x) => x.slice(1, -1));
  const isStatic = params.length === 0;
  const literal = s.segments.filter((x) => !x.startsWith("["));
  const urlExpr = isStatic
    ? `"/${literal.join("/")}"`
    : "`/" + [...literal.map((l) => l), ...params.map((p) => `\${p.${p}}`)].join("/") + "`";

  const header =
    `// Generated by scripts/gen-routes.ts — do not hand-edit.\n` +
    `// Archetype: ${s.archetype} · hub: ${s.hub}\n` +
    `import type { Metadata } from "next";\n` +
    `import { builtUrlsFor, metadataFor, renderPage } from "@/lib/render/page";\n\n`;

  if (isStatic) {
    return header +
      `const URL_PATH = ${urlExpr};\n\n` +
      `export const dynamic = "force-static";\n\n` +
      `export function generateMetadata(): Metadata {\n` +
      `  return metadataFor(URL_PATH);\n}\n\n` +
      `export default function Page() {\n` +
      `  return renderPage(URL_PATH, null);\n}\n`;
  }

  const paramType = params.map((p) => `${p}: string`).join("; ");
  const fromUrl = params
    .map((p, i) => `      ${p}: parts[${literal.length + i}]!,`)
    .join("\n");

  return header +
    `type Params = { ${paramType} };\n\n` +
    `export const dynamic = "force-static";\n` +
    `export const dynamicParams = false;\n\n` +
    `export function generateStaticParams(): Params[] {\n` +
    `  return builtUrlsFor("${s.archetype}").map((url) => {\n` +
    `    const parts = url.split("/").filter(Boolean);\n` +
    `    return {\n${fromUrl}\n    };\n` +
    `  });\n}\n\n` +
    `function urlFor(p: Params): string {\n  return ${urlExpr};\n}\n\n` +
    `export async function generateMetadata(\n` +
    `  { params }: { params: Promise<Params> },\n` +
    `): Promise<Metadata> {\n` +
    `  return metadataFor(urlFor(await params));\n}\n\n` +
    `export default async function Page({ params }: { params: Promise<Params> }) {\n` +
    `  return renderPage(urlFor(await params), null);\n}\n`;
}

function main(): void {
  if (existsSync(SITE_DIR)) rmSync(SITE_DIR, { recursive: true });
  const all = shapes();
  for (const s of all) {
    const file = join(SITE_DIR, ...s.segments, "page.tsx");
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, routeSource(s), "utf8");
  }
  console.log(`[routes] wrote ${all.length} route file(s) under app/(site)/`);
  for (const s of all.sort((a, b) => a.segments.join("/").localeCompare(b.segments.join("/")))) {
    console.log(`  /${s.segments.join("/")}  (${s.archetype})`);
  }
}

main();
