// Generated by scripts/gen-routes.ts — do not hand-edit.
// Archetype: teardown · hub: teardowns
import type { Metadata } from "next";
import { builtUrlsFor, metadataFor, renderPage } from "@/lib/render/page";

type Params = { app: string; lens: string };

export const dynamic = "force-static";
export const dynamicParams = false;

export function generateStaticParams(): Params[] {
  return builtUrlsFor("teardown").map((url) => {
    const parts = url.split("/").filter(Boolean);
    return {
      app: parts[1]!,
      lens: parts[2]!,
    };
  });
}

function urlFor(p: Params): string {
  return `/teardowns/${p.app}/${p.lens}`;
}

export async function generateMetadata(
  { params }: { params: Promise<Params> },
): Promise<Metadata> {
  return metadataFor(urlFor(await params));
}

export default async function Page({ params }: { params: Promise<Params> }) {
  return renderPage(urlFor(await params), null);
}
