// Generated by scripts/gen-routes.ts — do not hand-edit.
// Archetype: growth · hub: growth
import type { Metadata } from "next";
import { builtUrlsFor, metadataFor, renderPage } from "@/lib/render/page";

type Params = { problem: string; appType: string };

export const dynamic = "force-static";
export const dynamicParams = false;

export function generateStaticParams(): Params[] {
  return builtUrlsFor("growth").map((url) => {
    const parts = url.split("/").filter(Boolean);
    return {
      problem: parts[1]!,
      appType: parts[2]!,
    };
  });
}

function urlFor(p: Params): string {
  return `/growth/${p.problem}/${p.appType}`;
}

export async function generateMetadata(
  { params }: { params: Promise<Params> },
): Promise<Metadata> {
  return metadataFor(urlFor(await params));
}

export default async function Page({ params }: { params: Promise<Params> }) {
  return renderPage(urlFor(await params), null);
}
