// Generated by scripts/gen-routes.ts — do not hand-edit.
// Archetype: hub · hub: compare
import type { Metadata } from "next";
import { builtUrlsFor, metadataFor, renderPage } from "@/lib/render/page";

const URL_PATH = "/compare";

export const dynamic = "force-static";

export function generateMetadata(): Metadata {
  return metadataFor(URL_PATH);
}

export default function Page() {
  return renderPage(URL_PATH, null);
}
