// Generated by scripts/gen-routes.ts — do not hand-edit.
// Archetype: glossary · hub: glossary
import type { Metadata } from "next";
import { builtUrlsFor, metadataFor, renderPage } from "@/lib/render/page";

type Params = { slug: string };

export const dynamic = "force-static";
export const dynamicParams = false;

export function generateStaticParams(): Params[] {
  return builtUrlsFor("glossary").map((url) => {
    const parts = url.split("/").filter(Boolean);
    return {
      slug: parts[1]!,
    };
  });
}

function urlFor(p: Params): string {
  return `/glossary/${p.slug}`;
}

export async function generateMetadata(
  { params }: { params: Promise<Params> },
): Promise<Metadata> {
  return metadataFor(urlFor(await params));
}

export default async function Page({ params }: { params: Promise<Params> }) {
  return renderPage(urlFor(await params), null);
}
